# --- STAGE 1: Build ---
FROM node:18-alpine as builder

WORKDIR /app

# Copia e installa dipendenze
COPY package*.json ./
RUN npm ci

# Copia il codice
COPY . .

# Compila l'applicazione per la produzione
# Questo userà la "homepage": "/chatbot" definita nel package.json
RUN npm run build


# --- STAGE 2 ---
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80